title: @reesLABS
author: Rees
email: reeslabs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  So Im new to coding and developing and have dreams of making virtual assistant developments at my lab. 

# social links
twitter_username: reeslabs # DO NOT include the @ character, or else the build will fail!
github_username:  reeslabs # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
